### ISSUE TITLE
Parse git diff fails for some pull requests

### ISSUE THREAD

**Issue by wiseeker** [mibexsoftware/sonar-bitbucket-plugin#8] opened 2016-01-04 18:40 UTC
Exception `Failed to parse git diff: string matching regex '\z' expected but \n found` is thrown for one of my pull requests. This consistently happens every time whereas another relatively very small pull request succeeds.

Let me know if the full bitbucket diff would be useful.

Here is the stack trace:

`org.sonar.runner.impl.RunnerException: Unable to execute Sonar
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
INFO: ------------------------------------------------------------------------
	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
	at org.sonar.runner.api.Runner.execute(Runner.java:100)
	at org.sonar.runner.Main.executeTask(Main.java:70)
	at org.sonar.runner.Main.execute(Main.java:59)
	at org.sonar.runner.Main.main(Main.java:53)
Caused by: java.lang.RuntimeException: [sonar4bitbucket] Failed to parse git diff: string matching regex `\z' expected but `
' found
 	at ch.mibex.bitbucket.sonar.diff.IssuesOnChangedLinesFilter.parseOrFail(IssuesOnChangedLinesFilter.scala:48)
	at ch.mibex.bitbucket.sonar.diff.IssuesOnChangedLinesFilter.filter(IssuesOnChangedLinesFilter.scala:19)
	at ch.mibex.bitbucket.sonar.review.ReviewCommentsCreator.processIssues(ReviewCommentsCreator.scala:74)
	at ch.mibex.bitbucket.sonar.review.ReviewCommentsCreator.createOrUpdateComments(ReviewCommentsCreator.scala:28)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$executeOn$1.apply(SonarReviewPostJob.scala:21)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$executeOn$1.apply(SonarReviewPostJob.scala:18)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob.executeOn(SonarReviewPostJob.scala:18)
	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:65)
	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:55)
	at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:107)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:100)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:85)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:258)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:253)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:243)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:100)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:85)
	at org.sonar.batch.bootstrap.GlobalContainer.executeAnalysis(GlobalContainer.java:153)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:110)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:76)
	at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
	... 9 more
ERROR: 
ERROR: Re-run SonarQube Runner using the -X switch to enable full debug logging.
The sonar-runner did not complete successfully`

**Comment by ganesanr** [comment] 2016-01-04 18:42
This issue seems related to SO post http://stackoverflow.com/questions/1798738/scala-parser-token-delimiter-problem

**Comment by asdluki** [comment] 2016-01-07 12:35
I have the same problem. 

[sonar4bitbucket] Failed to parse git diff: string matching regex `\z' expected but `
' found

my stack trace:

Caused by: java.lang.RuntimeException: [sonar4bitbucket] Failed to parse git diff: string matching regex `\z' expected but `
' found
	at ch.mibex.bitbucket.sonar.diff.IssuesOnChangedLinesFilter.parseOrFail(IssuesOnChangedLinesFilter.scala:48)
	at ch.mibex.bitbucket.sonar.diff.IssuesOnChangedLinesFilter.filter(IssuesOnChangedLinesFilter.scala:19)
	at ch.mibex.bitbucket.sonar.review.ReviewCommentsCreator.processIssues(ReviewCommentsCreator.scala:76)
	at ch.mibex.bitbucket.sonar.review.ReviewCommentsCreator.createOrUpdateComments(ReviewCommentsCreator.scala:30)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$executeOn$1.apply(SonarReviewPostJob.scala:21)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$executeOn$1.apply(SonarReviewPostJob.scala:18)
	at scala.collection.immutable.List.foreach(List.scala:381)

**Comment by mrueegg** [comment] 2016-01-07 12:51
In order to reproduce this issue, the diff for this pull request would be very helpful.

First, please execute this cURL statement:

curl -v -u YOUR_BITBUCKET_USER  https://api.bitbucket.org/2.0/repositories/YOUR_USER_NAME/REPO_SLUG/pullrequests/PULL_REQUEST_ID/diff

then copy the URL from the Location Header field in the HTTP response (LOCATION_URL below) and use that with the appended “?context=0” parameter for the second cURL:

curl -u YOUR_BITBUCKET_USER  LOCATION_URL?context=0

The output of this second cURL statement would be the one of interest. Thanks in advance!

**Comment by asdluki** [comment] 2016-01-07 13:20
attached file with output of "diff"

[diff_response.txt](https://github.com/mibexsoftware/sonar-bitbucket-plugin/files/81186/diff_response.txt)

**Comment by asdluki** [comment] 2016-01-20 12:26
Hi,
i think that i detect problem.

Problem is "\ No Newline at End of File" on git diff.

Each our pull request on bitbucket who have "\ No Newline at End of File" on diff doesn't work with your plugin. 

Maybe it will be helpful

**Comment by mrueegg** [comment] 2016-01-25 08:39
Hi,

Please excuse me for getting back to you that late!

@asdluki I wasn't able yet to reproduce this issue with your diff_response.txt file. In my tests, the parser is able to parse this file. It doesn't contain a "\ No Newline at End of File". Although I have a rule for the no newline case in the parser, it could be that it fails in certain scenarios. Is it often the case that the parser is not able to handle your pull requests? Could you please give me another example where the parser failed due to the no newline issue? That would be very helpful!

@wiseeker Could you please provide me a diff as explained above for a pull request where the plug-in fails? That would be very helpful!

**Comment by tajain** [comment] 2016-01-25 11:40
Hi @mrueegg,

I've faced same problem when diff encounters "\ No newline at end of file". One such sanitized sample is attached for reference.

Rgds,
TJ
[diff.txt](https://github.com/mibexsoftware/sonar-bitbucket-plugin/files/103139/diff.txt)

**Comment by asdluki** [comment] 2016-01-25 11:47
Hi @mrueegg 

thanks for reply.

This problem occurs quite often in our "pull request". 

i attached files with other examples.

[diff_wrong1.txt](https://github.com/mibexsoftware/sonar-bitbucket-plugin/files/103143/diff_wrong1.txt)
[diff_wrong2.txt](https://github.com/mibexsoftware/sonar-bitbucket-plugin/files/103144/diff_wrong2.txt)
[diff_wrong3.txt](https://github.com/mibexsoftware/sonar-bitbucket-plugin/files/103145/diff_wrong3.txt)

Regards,
Luk

**Comment by mrueegg** [comment] 2016-01-25 13:18
Hi,

thanks a lot for the examples.

@tajain I was able to fix this issue. It was caused by the fact that apparently a line like
\ No newline at end of file
can appear at any position not just at the end of a file diff. Do you mind if I use your example as a test case which would mean that it will be part of this Github repository?

@asdluki My parser now runs all 3 of your examples after the mentioned fix. Do you mind if I use diff_wrong1.txt and diff_wrong3.txt as test cases which would mean that they will be part of this Github repository?

**Comment by tajain** [comment] 2016-01-25 13:24
Thks @mrueegg for analysis. Pls feel free to use the previously attached sample for tests as this is sanitized already.

**Comment by asdluki** [comment] 2016-01-25 13:47
no problem, feel free to use my sample diff for test cases.

**Comment by mrueegg** [comment] 2016-01-25 14:55
Please see version 1.0.7 which includes the bug fix for this issue.

**Comment by wiseeker** [comment] 2016-01-25 15:20
Thank you Michael for your efforts. I already sent two diffs by email: one
passing and one falling.

Did you not receive the email or do you want more diffs?

Thanks,
Ganesh

**Comment by mrueegg** [comment] 2016-01-25 15:34
@wiseeker Excuse me, you are right, I found it. The problem with the FailingDiff.txt is that the context lines do not start with a single space, e.g. see <?xml and <Project:

```
+?
<?xml version="1.0" encoding="utf-8"?>
+
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
```
According to the Git diff documentation, this should be the case. Do you have any idea why there is no space in front of context lines in this file?

**Comment by tajain** [comment] 2016-01-25 18:45
Hi @mrueegg 

I found another case where issue is replicable - new file mode (a sample is attached). Plugin (v1.0.7) is reporting "java.lang.RuntimeException: [sonar4bitbucket] Failed to parse git diff: string matching regex `\z' expected but"
[diff_newFile.txt](https://github.com/mibexsoftware/sonar-bitbucket-plugin/files/103684/diff_newFile.txt)

**Comment by wiseeker** [comment] 2016-01-25 19:53
Hi @mrueegg,
Upon close inspection I believe those are not context lines. Rather, real diff lines are moved to next line due to extra CR/LF. Please see the attached image.

No extra CR/LF issue in the PassingDiff.txt. I'm trying to look around to learn why this happened with one of my pull request but not with other. If you have some clue, I would be glad to know.

![capture](https://cloud.githubusercontent.com/assets/9583714/12562435/03d3381e-c35a-11e5-839e-7bbf88a352ec.JPG)

**Comment by mrueegg** [comment] 2016-01-26 10:19
@tajain Unfortunately, I was not able to reproduce this issue with 1.0.7. Could you please provide me the full stack trace?

**Comment by asdluki** [comment] 2016-01-27 10:12
Hi,

I'm still having the same problem with version 1.0.7.

git diff: [diff_wrong4.txt](https://github.com/mibexsoftware/sonar-bitbucket-plugin/files/106391/diff_wrong4.txt)


Stack trace:
ERROR: Error during Sonar runner execution
org.sonar.runner.impl.RunnerException: Unable to execute Sonar
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
	at org.sonar.runner.api.Runner.execute(Runner.java:100)
	at org.sonar.runner.Main.executeTask(Main.java:70)
	at org.sonar.runner.Main.execute(Main.java:59)
	at org.sonar.runner.Main.main(Main.java:53)
**Caused by: java.lang.RuntimeException: [sonar4bitbucket] Failed to parse git diff: string matching regex `\z' expected but `**
' found
	at ch.mibex.bitbucket.sonar.diff.IssuesOnChangedLinesFilter.parseOrFail(IssuesOnChangedLinesFilter.scala:48)
	at ch.mibex.bitbucket.sonar.diff.IssuesOnChangedLinesFilter.filter(IssuesOnChangedLinesFilter.scala:19)
	at ch.mibex.bitbucket.sonar.review.ReviewCommentsCreator.processIssues(ReviewCommentsCreator.scala:76)
	at ch.mibex.bitbucket.sonar.review.ReviewCommentsCreator.createOrUpdateComments(ReviewCommentsCreator.scala:30)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$executeOn$1.apply(SonarReviewPostJob.scala:21)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$executeOn$1.apply(SonarReviewPostJob.scala:18)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob.executeOn(SonarReviewPostJob.scala:18)
	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:65)
	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:55)
	at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:107)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:100)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:85)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:258)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:253)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:243)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:100)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:85)
	at org.sonar.batch.bootstrap.GlobalContainer.executeAnalysis(GlobalContainer.java:153)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:110)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:76)
	at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
	... 9 more

**Comment by mrueegg** [comment] 2016-02-03 13:14
@asdluki I wasn't able to reproduce this with your file. Has this happened again lately?

**Comment by mborodin** [comment] 2016-02-10 15:30
Hello,
I have the same issue on both v1.0.7 and v1.0.8.
I'm not allowed to provide diff file :( But I can say, that it contains multiple entries "\ No newline at end of file" and contains Chinese unicode characters.

**Comment by mrueegg** [comment] 2016-02-10 15:49
@mborodin Thanks for your feedback. You don't need to provide me the full diff. If you could just send me the multiple "\ No newline at end of file" lines and 1-2 lines of your Chinese unicode characters that would probably already suffice to reproduce this.

**Comment by jdimanche** [comment] 2016-02-11 09:32
I'm having the same error on few PR (10%) : [sonar4bitbucket] Failed to parse git diff: string matching regex `\z' expected but `
' found

Here are 2 diffs :


[diff_pr_153_ko.diff.txt](https://github.com/mibexsoftware/sonar-bitbucket-plugin/files/126126/diff_pr_153_ko.diff.txt)
[diff_pr_90_ko.diff.txt](https://github.com/mibexsoftware/sonar-bitbucket-plugin/files/126127/diff_pr_90_ko.diff.txt)

**Comment by mrueegg** [comment] 2016-02-11 18:11
Thanks for your diff. I'm pretty sure that this was caused by Windows newlines (i.e., by the carriage return character). I've fixed the parser now and will release a new version of the plug-in.

**Closed** 2016-02-11 18:25 UTC

**Comment by jdimanche** [comment] 2016-03-02 09:03
Hello,

I have 2 another 'Failed to parse git diff'.
I'm using version 1.1.0.

## **First one :**
**Stack trace :**
```
[sonar4bitbucket] Failed to parse git diff: ` b/' expected but ` ' found
	at ch.mibex.bitbucket.sonar.diff.IssuesOnChangedLinesFilter.parseOrFail(IssuesOnChangedLinesFilter.scala:48)
	at ch.mibex.bitbucket.sonar.diff.IssuesOnChangedLinesFilter.filter(IssuesOnChangedLinesFilter.scala:19)
	at ch.mibex.bitbucket.sonar.review.ReviewCommentsCreator.processIssues(ReviewCommentsCreator.scala:76)
	at ch.mibex.bitbucket.sonar.review.ReviewCommentsCreator.createOrUpdateComments(ReviewCommentsCreator.scala:30)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$executeOn$1.apply(SonarReviewPostJob.scala:21)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$executeOn$1.apply(SonarReviewPostJob.scala:18)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob.executeOn(SonarReviewPostJob.scala:18)
	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:65)
	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:55)
	at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:107)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:185)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:243)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:238)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:228)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:55)
	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:79)
	at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)****
```

**Diff file :**
[diff_case_1.txt](https://github.com/mibexsoftware/sonar-bitbucket-plugin/files/154332/diff_case_1.txt)

## Second one
```
Caused by: java.lang.RuntimeException: [sonar4bitbucket] Failed to parse git diff: string matching regex `\z' expected but ` ' found
	at ch.mibex.bitbucket.sonar.diff.IssuesOnChangedLinesFilter.parseOrFail(IssuesOnChangedLinesFilter.scala:48)
	at ch.mibex.bitbucket.sonar.diff.IssuesOnChangedLinesFilter.filter(IssuesOnChangedLinesFilter.scala:19)
	at ch.mibex.bitbucket.sonar.review.ReviewCommentsCreator.processIssues(ReviewCommentsCreator.scala:76)
	at ch.mibex.bitbucket.sonar.review.ReviewCommentsCreator.createOrUpdateComments(ReviewCommentsCreator.scala:30)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$executeOn$1.apply(SonarReviewPostJob.scala:21)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$executeOn$1.apply(SonarReviewPostJob.scala:18)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob.executeOn(SonarReviewPostJob.scala:18)
	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:65)
	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:55)
	at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:107)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:185)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:243)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:238)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:228)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:55)
	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:79)
	at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
	... 9 more
```

**Diff file :**
[diff_case_2.txt](https://github.com/mibexsoftware/sonar-bitbucket-plugin/files/154359/diff_case_2.txt)
